name = "qq-music-api"
main = "src/index.js"
compatibility_date = "2024-01-01"

# D1 数据库绑定
[[d1_databases]]
binding = "DB"
database_name = "qq-music-api"
database_id = "1dfc3373-ec1d-4fbe-9113-104a4d0d1784" 

# 定时刷新凭证 (每天凌晨 3 点)
[triggers]
crons = ["0 3 * * *"]


# 开启日志
[observability]
[observability.logs]
enabled = true
invocation_logs = true

[vars]
# 本地开发可直接填写，线上建议在 Cloudflare Secrets 中设置 password
password = ""
